name: CI - run fuzzing

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  fuzz:
    runs-on: ubuntu-latest

    steps:
      # Checks out the repository
      - name: Check out code
        uses: actions/checkout@v4

      # Sets up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Installs dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install GitPython pandas numpy

      # Runs fuzzing script
      - name: Run fuzz.py
        run: |
          python fuzz.py
